.TH "Reference k adresáři src/kalosha/geomdedicnost" 3 "út 12. kvě 2020" "Cvičení" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reference k adresáři src/kalosha/geomdedicnost
.SH SYNOPSIS
.br
.PP
.SS "Soubory"

.in +1c
.ti -1c
.RI "soubor \fBCtverec\&.java\fP"
.br
.ti -1c
.RI "soubor \fBGeomObj\&.java\fP"
.br
.ti -1c
.RI "soubor \fBKruh\&.java\fP"
.br
.ti -1c
.RI "soubor \fBObdelnik\&.java\fP"
.br
.ti -1c
.RI "soubor \fBTrojuhelnik\&.java\fP"
.br
.in -1c
