.TH "kalosha.geomdedicnost.GeomObj" 3 "út 12. kvě 2020" "Cvičení" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kalosha.geomdedicnost.GeomObj
.SH SYNOPSIS
.br
.PP
.PP
Zděděna třídami \fBkalosha\&.geomdedicnost\&.Ctverec\fP, \fBkalosha\&.geomdedicnost\&.Kruh\fP, \fBkalosha\&.geomdedicnost\&.Obdelnik\fP a \fBkalosha\&.geomdedicnost\&.Trojuhelnik\fP\&.
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "abstract double \fBgetPlocha\fP ()"
.br
.ti -1c
.RI "abstract double \fBgetObvod\fP ()"
.br
.in -1c
.SH "Dokumentace k metodám"
.PP 
.SS "abstract double kalosha\&.geomdedicnost\&.GeomObj\&.getObvod ()\fC [abstract]\fP"

.PP
\fBNávratová hodnota\fP
.RS 4
vrati obvod figury 
.RE
.PP

.PP
Reimplementováno v \fBkalosha\&.geomdedicnost\&.Trojuhelnik\fP, \fBkalosha\&.geomdedicnost\&.Obdelnik\fP, \fBkalosha\&.geomdedicnost\&.Ctverec\fP a \fBkalosha\&.geomdedicnost\&.Kruh\fP\&.
.SS "abstract double kalosha\&.geomdedicnost\&.GeomObj\&.getPlocha ()\fC [abstract]\fP"

.PP
\fBNávratová hodnota\fP
.RS 4
vrati plochu figury 
.RE
.PP

.PP
Reimplementováno v \fBkalosha\&.geomdedicnost\&.Trojuhelnik\fP, \fBkalosha\&.geomdedicnost\&.Obdelnik\fP, \fBkalosha\&.geomdedicnost\&.Ctverec\fP a \fBkalosha\&.geomdedicnost\&.Kruh\fP\&.

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Cvičení\&.
