.TH "kalosha.geomdedicnost" 3 "út 12. kvě 2020" "Cvičení" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kalosha.geomdedicnost
.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBCtverec\fP"
.br
.ti -1c
.RI "class \fBGeomObj\fP"
.br
.ti -1c
.RI "class \fBKruh\fP"
.br
.ti -1c
.RI "class \fBObdelnik\fP"
.br
.ti -1c
.RI "class \fBTrojuhelnik\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Cvičení\&.
