.TH "kalosha" 3 "út 12. kvě 2020" "Cvičení" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kalosha
.SH SYNOPSIS
.br
.PP
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBapps\fP"
.br
.ti -1c
.RI "package \fBgeomdedicnost\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Cvičení\&.
