.TH "kalosha.geomdedicnost.Kruh" 3 "út 12. kvě 2020" "Cvičení" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kalosha.geomdedicnost.Kruh
.SH SYNOPSIS
.br
.PP
.PP
Dědí z bázové třídy \fBkalosha\&.geomdedicnost\&.GeomObj\fP\&.
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "\fBKruh\fP (double \fBr\fP)"
.br
.ti -1c
.RI "double \fBgetPlocha\fP ()"
.br
.ti -1c
.RI "double \fBgetObvod\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Privátní atributy"

.in +1c
.ti -1c
.RI "double \fBr\fP"
.br
.in -1c
.SH "Dokumentace konstruktoru a destruktoru"
.PP 
.SS "kalosha\&.geomdedicnost\&.Kruh\&.Kruh (double r)"

.SH "Dokumentace k metodám"
.PP 
.SS "double kalosha\&.geomdedicnost\&.Kruh\&.getObvod ()"

.PP
\fBNávratová hodnota\fP
.RS 4
vrati obvod figury 
.RE
.PP

.PP
Reimplementuje stejnojmenný prvek z \fBkalosha\&.geomdedicnost\&.GeomObj\fP\&.
.SS "double kalosha\&.geomdedicnost\&.Kruh\&.getPlocha ()"

.PP
\fBNávratová hodnota\fP
.RS 4
vrati plochu figury 
.RE
.PP

.PP
Reimplementuje stejnojmenný prvek z \fBkalosha\&.geomdedicnost\&.GeomObj\fP\&.
.SS "String kalosha\&.geomdedicnost\&.Kruh\&.toString ()"

.PP
\fBNávratová hodnota\fP
.RS 4
vrati popis figury ve tvare 'Kruh{ r = x; Obvod = y ; Plocha = z}' 
.RE
.PP

.SH "Dokumentace k datovým členům"
.PP 
.SS "double kalosha\&.geomdedicnost\&.Kruh\&.r\fC [private]\fP"
polomer kruhu 

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Cvičení\&.
